# Références

[**ACIA. (2014a)**](https://www.inspection.gc.ca/salubrite-alimentaire-pour-l-industrie/directives-archivees-sur-les-aliments/non-enregistre-au-federal/inspection-des-produits/manuel-d-inspection/fra/1393949957029/1393950086417?chap=5). Agence Canadienne d'Inspection des Aliments. Dangers pour la salubrité des aliments.

[**ACIA. (2014b)**](https://www.inspection.gc.ca/sante-des-animaux/aliments-du-betail/consultations/identification-des-dangers-des-aliments-du-betail/fra/1399399411768/1399399412471#a31). Agence Canadienne d'Inspection des Aliments. Identification des dangers des aliments du bétail et mesures préventives - Proposition de cadre de réglementation.

**Alexander, J., Auounsson, G. A., Benford, D., & Cockburn, A. (2008)**. Mercury as undesirable substance in animal feed - Scientific opinion of the Panel on Contaminants in the Food Chain. _The EFSA Journal_, 654, 1-76. 

**Alexander, J., Benford, D., Cockburn, A., & Cravedi, J. P. (2008)**. Gossypol as undesirable substance in animal feed - Scientific Opinion of the Panel on Contaminants in the Food Chain. **The EFSA Journal, 908, 1-55**. 

**Blancou, J. (1978)**. Fermentation microbienne de produits végétaux destinés à l'alimentation du bétail au Sénégal. I Etude bactériologique et biochimique. _Rev. Élev. Méd. vét. Pays trop._, 31(2), 213-218.

**Blancou, J., & Calvet, H. (1979)**. Fermentation microbienne de produits végétaux destinés à l'alimentation du bétail au Sénégal. II - Application à l'amélioration de la digestibilité in vivo. _Rev. Élev. Méd. vét. Pays trop._, 32(1), 77-80. 

**Chateau-Degat, M. L. (2003)**. Les toxines marines : problèmes de santé en émergence. _VertigO - la revue électronique en sciences de l'environnement_, 4(1), 1-11. 

**Leverve, X. (2010)**. Alimentation : les différentes facettes de la qualité. La chimie et l'alimentation, 1-13. 

[**OIE. (2020)**](https://www.oie.int/fr/pour-les-medias/une-seule-sante/). Organisation Mondiale de la Santé Animale. Une seule santé.

[**Santé Canada. (2016)**](https://www.canada.ca/fr/sante-canada/services/aliments-nutrition/salubrite-aliments/additifs-alimentaires.html). Additifs alimentaires.

[**Santé Canada. (2018)**](https://www.canada.ca/fr/sante-canada/services/medicaments-produits-sante/medicaments-veterinaires.html). Médicaments vétérinaires.

[**Santé Canada. (2019)**](https://www.canada.ca/fr/sante-canada/services/aliments-nutrition/salubrite-aliments/contaminants-chimiques/contaminants-environnementaux.html). Contaminants environnementaux.

[**Santé Canada. (2020)**](https://www.canada.ca/fr/sante-canada/services/aliments-nutrition/salubrite-aliments/contaminants-chimiques/toxines-naturelles.html). Toxines naturelles.

**Sutter, S. (2017)**. Valorisation du tourteau de colza par fermentation en milieu solide pour une application en alimentation animale. (Doctorat), Bourgogne Franche-Comté, (017UBFCK023).


<div align = "center">**[Chapitre 1](https://git.io/Jk9Ck) | [Chapitre 2](https://git.io/Jk9Cs) | [Chapitre 3](https://git.io/Jk9Cn) | [Chapitre 4](https://git.io/Jk9CE) | [Chapitre 5](https://git.io/Jk9C2) | [Chapitre 6](https://git.io/Jk9CV) | [Chapitre 7](https://git.io/Jk9C6) | [Chapitre 8](https://git.io/Jk9Ci)**</div>